### PR TITLE
no need for BC

### PR DESCRIPTION
**Pull request by cordoval**

### CODE REVIEW

**Comment by sstok** [comment]
The composer.json needs to be updated as well, remember that it only generates warnings but still works in Symfony 3.0 :+1: there are more types then this one that need updating.

**Comment by cordoval** [comment]
in symfony 3.0 it will be removed so it does not work

**Comment by sstok** [comment]
`if ($resolver instanceof OptionsResolverInterface) {` ;) this is the trick, Symfony 3 removed the interface so it will use the newer API. Travis already confirms that is works.

https://travis-ci.org/rollerworks/search/jobs/108538312
https://travis-ci.org/rollerworks/search/jobs/108538312#L197

Symfony 3 support is pré for me as Park-Manager is Symfony 3+ only :+1:

**Comment by cordoval** [comment]
please update the library so it does not show up warnings

**Comment by sstok** [comment]
Closing in favor of #89

**Comment by sstok** [comment]
Version 1.1.0 is now released.

**Pull request closed without merging**
