### PR TITLE
Remove PHPSpec in favor of PHPUnit

### PR DESCRIPTION
**Pull request by sstok**
|Q            |A  |
|---          |---|
|Bug Fix?     |no |
|New Feature? |no |
|BC Breaks?   |no |
|Deprecations?|no |
|Fixed Tickets|   |
|License      |MIT|

### CODE REVIEW

**Comment by cordoval** [comment]
:+1:

**Comment by cordoval** [comment]
:+1: i approve

**Comment by sstok** [comment]
Please the reactions button :wink: https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments

**Comment by cordoval** [comment]
I know i realize about those, i am old school though

**Comment by sstok** [comment]
Not all classes are moved to PHPUnit, but those are planned for deprecation anyway :)
Except for ResolvedFieldType, but I'm tired of this pr so will keep that one for a lazy Sunday.

**Pull request merged**
